apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: edge-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - name: processor
        image: ghcr.io/elh-bayat/edge-traffic-monitor/processor:latest
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: DATABASE_URL
          value: "postgresql://traffic:traffic123@postgres:5432/trafficdb"
